Fix certbot error by 'systemctl restart docker'
This commits fixes certbot conection error
("failed to establish a new connection") by running
'systemctl restart docker'.

Details:

After some inspection, it turned out that the error
is caused because docker containers could not have
sent outgoing network traffic with the error
("iptables: no chain/target/match by that name").

In this case 'systemctl restart docker' for resetting
iptables internal state worked, as described in
https://www.cyberciti.biz/faq/how-to-install-curl-on-alpine-linux.

The original certbot error:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host=acme-v02.api.letsencrypt.org 9, port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcd8f74a3a0>: Failed to establish a new connection: [Errno -3] Try again))

Similar issue case:

https://community.letsencrypt.org/t/connectionerror-httpsconnectionpool-host-acme-v02-api-letsencrypt-org-port-443/120105